name: sanemi
services:
- name: client
  source_dir: /
  github:
    repo: bondanherumurti-transfez/zoom-app-hello-world
    branch: main
    deploy_on_push: true
  run_command: serve -s build -l 8080
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  build_command: npm run build
  http_port: 8080
  routes:
  - path: /
  headers:
  - key: Strict-Transport-Security
    value: max-age=31536000; includeSubDomains
  - key: X-Content-Type-Options
    value: nosniff
  - key: Content-Security-Policy
    value: "default-src 'self'; script-src 'self' 'unsafe-inline' https://appssdk.zoom.us; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://zoom.us https://*.zoom.us; frame-ancestors 'self' https://zoom.us https://*.zoom.us"
  - key: Referrer-Policy
    value: strict-origin-when-cross-origin
  - key: X-Frame-Options
    value: SAMEORIGIN
  - key: X-XSS-Protection
    value: "1; mode=block"